services:
  workers:
    build:
      context: .
      dockerfile: apps/workers/Dockerfile
    env_file:
      - apps/workers/.env
    deploy:
      replicas: 3
      mode: replicated
    networks:
      - app-network
    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_started

  web-api:
    build:
      context: .
      dockerfile: apps/web-api/Dockerfile
    ports:
      - "80:80"
    env_file:
      - apps/web-api/.env
    networks:
      - app-network
    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_started

  postgres:
    image: postgres:16.4
    networks:
      - app-network
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - ./packages/adapters/src/repositories/drizzle/0000_nasty_vision.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7.4.1-alpine
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
